[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "https://sepolia.gateway.tenderly.co"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
